### ISSUE TITLE
Huawei RIL

### ISSUE THREAD

**Issue by omerazo** [Meticulus/android_device_huawei_hi6250#1]
So it seems the Honor 6 RIL class won't work.

Huawei adopted some of the Android code for RIL, for example,

>  private Object responseSignalStrength(final Parcel parcel) {
>         return SignalStrength.makeSignalStrengthFromRilParcel(parcel);
>    }

My knowledge about RIL is pretty much none, does the logs give enough information on the last message that wasn't handled properly?

* Procyon decompiles most of the functions, though a few functions like RILReceiver::run will result in bytecode. (I guess it can't handle nested exceptions properly)

**Comment by Meticulus** [comment]
RIl is up!
