### ISSUE TITLE
Instruction Suggestions

### ISSUE THREAD

**Issue by lemacx** [Meticulus/android_device_huawei_hi6250#10]
Hey, first of all thanks for the awesome How-To!

I used it to build the current version of LineageOS and noticed a few things during the process which might be helpful for others. For building I set up a Ubuntu 16.04 LTS using Hyper-V. The first suggestion is to outline the required amount of free disk space - after the build my VHDD had about 110GB (just clean install and repo + data from the compile process). I underestimated it in the beginning (just had it set to about 60GB) which broke the build various times.

I built the image without the 4GB-RAM restriction for Jack, and at peak it used about 10GB of RAM, so everything above should be save.

Two small typos are regarding `sudo apt-get install imagemagick` - which should be all lowercase as I encountered - and the line for inclusion of the Meticulus Extras 
`<project name="Meticulus/android_packages_apps_CodinalteParts" path="packages/apps/CodinalteParts" remote="github" revision="hi6250"/>`
where "apps" was missing after "packages" in the name.

Just as a reference for others, on my machine (i7 4720HQ, 16GB RAM, HDD) the build took 2 hours 50 minutes.

After the sucessfull build I flashed the image to my VNS-L31 and everything worked like a charm!

Thanks again for this awesome manual and for open-sourcing your code Meticulus!

**Comment by Meticulus** [comment]
Thank you for your suggestions. I'm trying to keep the instructions for the lowest common denominator but I will update the typos and add a note about disk space... :+1:

**Comment by Meticulus** [comment]
https://github.com/Meticulus/android_device_huawei_hi6250/commit/1cd1966231a1a1477f76806c33d3c629fb9d9716
