### ISSUE TITLE
A build error

### ISSUE THREAD

**Issue by TheMarionette** [Meticulus/android_device_huawei_hi6250#3]
Hello! :D

I got this error while making a clean CM build:
http://hastebin.com/sasiroroku.sql

The error didn't occur in the past,and it started after I updated to the latest source(if I remember correctly,I was on source dating before November 24th and the rom built without a single problem back then).
I also tried making a fresh install of Ubuntu and initializing the build environment again,but the mentioned error persists.

**Comment by dady8889** [comment]
You need to apply this patch: https://github.com/Meticulus/android_device_huawei_hi6250/blob/master/patches/meticulus/build/0001-build-don-t-install-recovery-sh.patch
Meticulus moved his build patches to the meticulus folder because it's his personal settings.

**Comment by TheMarionette** [comment]
Thanks! :D

**Comment by Meticulus** [comment]
I didnt think that would be needed to complete a build.... Were you doing a clean build? or just installclean?

**Comment by Meticulus** [comment]
I think this is ultimately because recovery is not in the fstab...

**Comment by TheMarionette** [comment]
I made a fresh install of Ubuntu and initialized everything like I always did. I didn't modify anything.

**Comment by Meticulus** [comment]
I added recovery to the fstab. I think that should fix this issue but I'm not sure. I'll leave this open until someone can confirm.

https://github.com/Meticulus/android_device_huawei_hi6250/commit/f771594d33ca24fd716563114cdeb3fbe69ae91a

**Comment by TheMarionette** [comment]
Well,it builds now. But...it doesn't boot...

**Comment by Meticulus** [comment]
What happens?

**Comment by TheMarionette** [comment]
It simply loops on the boot animation.

**Comment by Meticulus** [comment]
I just released a build Beta 3 silently. Flash it, enable adb, then dirty flash yours on top of it and use adb to get a log

**Comment by TheMarionette** [comment]
Here is the log.
https://hastebin.com/ituvazuzuj.bash

**Comment by Meticulus** [comment]
Ah... I have seen this before in Beanstalk. I have not repo synced CM in a long time so they must have changed something... I'll add the patch from Beanstalk that fixes it but, I'll need to disable it until I repo sync CM. So, you just enable it OK.

**Comment by Meticulus** [comment]
OK, it's in. Just rename this file patches/cm/frameworks/base/0001-libhuawei_init-fix-for-cm.disabled

to

patches/cm/frameworks/base/0001-libhuawei_init-fix-for-cm.patch

and re-patch

**Comment by TheMarionette** [comment]
The patch fails at the automated procedure by patch.sh,even after I fixed its "coordination" line from 58 to 60. I patched the file manually,though.

**Comment by Meticulus** [comment]
I found a better solution:
https://github.com/Meticulus/android_device_huawei_hi6250/commit/f630d5a3a1652d26d93fc951df36bb1f00a9f5c5

**Comment by TheMarionette** [comment]
I am constantly getting this error:https://hastebin.com/oraqonibex.pas

**Comment by Meticulus** [comment]
IDK Man, There have been a lot of structural changes because I am working on sepolicy but I ran that build yesterday and everything seemed OK... I did add a commit to disable building rild and libril because we do not use the ones that are built from source. We are using the blobs...

https://github.com/Meticulus/android_vendor_huawei_hi6250/commit/012fb2ad1b37dc0caccd61ad99e23ca875cffaa3

https://github.com/Meticulus/android_device_huawei_hi6250/commit/96f6115c1b69ed73302eac95bd18fd8067d169ec

**Comment by TheMarionette** [comment]
Hmm,I got the same error even after syncing the newest things.

**Comment by Meticulus** [comment]
It will be awhile before I repo sync again. I want to finish sepolicy before I deal with new issues... Id just wait if I were you...

**Comment by TheMarionette** [comment]
No rush,I just wanted to give all the info.

**Comment by Meticulus** [comment]
repo syncing now...

**Comment by Meticulus** [comment]
I believe I've got this libril thing worked out now but you should switch the device tree to the cm-13.0 branch...

**Comment by TheMarionette** [comment]
I'll sync it right away. :D

**Comment by Meticulus** [comment]
I just ran a build yesterday and did not have this issue. This fixes it as far as I can tell https://github.com/Meticulus/android_device_huawei_hi6250/commit/f630d5a3a1652d26d93fc951df36bb1f00a9f5c5

**Comment by TheMarionette** [comment]
I don't understand,really,since that commit truly should fix it,but it won't boot no matter if I clear the /out directory or let it make a dirty build. The only possible reason which is left might be ccache,I will try clearing it and making another build in a day or so...

**Comment by TheMarionette** [comment]
Ookay,I got it fixed. :D

**Comment by Meticulus** [comment]
;)
