### ISSUE TITLE
Folder open at the bottom-center of the screen

### ISSUE THREAD

**Issue by Ansolix** [Meticulus/android_device_huawei_hi6250#6]
Device: Honor 5C
Build date: 20170222
Description of issue: When I open a folder, all they other apps and widget desappear until I close it, and it displays the folder at the bottom-center of the screen, wherever I move it.
Things I have tried: Move the folder, delete it then create a new one

(I'm looking for how to get it, i will modify the issue as soon as i get these 2 files)
Logcat log: 
Dmesg/kmsg log:

**Comment by Meticulus** [comment]
I believe this is the intended behavior.

**Comment by Ansolix** [comment]
Indeed that looks like a bug but i slowed the openning animation and that isn't you're right
