### ISSUE TITLE
[Q] About porting AOSP 7.0

### ISSUE THREAD

**Issue by hak86** [Meticulus/android_device_huawei_hi6250#7]
Hi
I'm trying to port aosp 7.1.2 on my Huawei P8 Lite 2017 that phone is use same soc of P9 Lite, but the only thing aren't same , it's the kernel my phone use Linux 4.1 that Huawei didn't release yet so I'm using prebuilt one already compatible with nougat.
I make a minimal device tree for booting process, the only thing still don't know how to "symlink" are blobs, the blobs of this phone are located in a folder called /vendor and the /system folder are contain just the firmware no libs related to phone, what should do in this case, should use libshim?
any help will be appreciated, thanks in advance.. 
![screenshot from 2017-05-01 19-07-59](https://cloud.githubusercontent.com/assets/6603252/25594876/ce8a04aa-2ec2-11e7-802f-339698977d6f.png)

**Comment by Meticulus** [comment]
It really depends on your fstab. If you have a vendor partition in the fstab then you should not have to do anything unless you want to modifiy the contents. If there is no vendor partition then you can copy these files to /system/vendor which is symlinked to /vendor in init.rc like this:

https://github.com/LineageOS/android_system_core/blob/cm-14.1/rootdir/init.rc#L46

Remember, there is no "should" in development. Do what works and what seems best to YOU and don't worry about "should" or what others say. ;)
