### ISSUE TITLE
Incomplete patches directory

### ISSUE THREAD

**Issue by Exagone313** [Meticulus/android_device_huawei_hi6250#8]
Hi,

I'd like to build a rom to this device and start experimenting, and it looks like you are the only developer working on this device.
It seems that the directory patches is incomplete, a directory `meticulus` is missing: https://gist.github.com/Exagone313/31e57c1b79b72aa9f4adaaea0bb9f013

I looked around your job and you does not seem happy to share your work, but it is necessary if you want other people to get involved. I'm ok to become a supporter via your support Paypal account, only if you share the source code with your builds (I'm interested by the source code, not the builds).

**Comment by Meticulus** [comment]
I was unaware that patcher was not working but it was simple to fix.

https://github.com/Meticulus/android_device_huawei_hi6250/commit/7f80f6a3608a94bd758cccc35e7c88fc2e58092e

Good luck.

**Comment by Exagone313** [comment]
Yes, now it's patching. Thanks for your reply in short time. I'm compiling to see if it works (assuming the actual version is compilable).

**Comment by Meticulus** [comment]
I don't think there have been any major changes in lineage 14.1, should build just find as long as patching succeeds... ;)

**Comment by Exagone313** [comment]
Just `meticulus-install-branding.patch` is not patching, if you're interested in keeping your branding (those are just text comments so not a big deal in the build process).

**Comment by dady8889** [comment]
@Exagone313 that branding should no longer work in newest android, because dex optimization is now handled without waiting, instead notification shows up.

**Comment by Meticulus** [comment]
@dady8889: I believe you are mistaken about the patch in question...

**Comment by dady8889** [comment]
@Meticulus isn't that the branding when you first boot the rom? if it's the build branding, yeah sorry :)

**Comment by Exagone313** [comment]
It's the text displayed on TWRP when flashing.

**Comment by dady8889** [comment]
@Exagone313 yeah, my mistake

**Comment by Meticulus** [comment]
@Exagone313 @dady8889 , The source is open now, you guys are not required to keep my customizations ( you can if you want ) and are free to post your own builds where ever you want. All I ask is that if you are going to publish your ROM publicly that you put some work in: Try to fix one of the remaining bugs, clean up some code, add new features...

I would appreciate it if you submit pull requests to keep these trees up and it seems prudent... 

Remember that this tree builds AOSP , OMNI , SLIM , RR and LINEAGE.

Have fun... ;)
